version: "3.8"

services:
  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ./ollama-models/blobs:/root/.ollama/models/blobs
      - ./ollama-models/manifests:/root/.ollama/models/manifests

  webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    depends_on:
      - ollama
    ports:
      - "3000:8080"
    environment:
      - OLLAMA_API_BASE_URL=http://ollama:11434
      - OPENWEBUI_DOCUMENTS_PATH=/app/documents/cyote_chunks
    volumes:
      - openwebui_data:/app/backend/data
      - ./chunks_md:/app/documents/cyote_chunks

volumes:
  openwebui_data:
